INSERT INTO PRODUCT(name, description, price) VALUES ('TENIS NIKE', 'PARA CORRIDAS LONGAS', 350)
INSERT INTO PRODUCT(name, description, price) VALUES ('TENIS ADIDAS', 'PARA CORRIDAS CURTAS', 300)
INSERT INTO PRODUCT(name, description, price) VALUES ('TENIS VANS', 'PARA O DIA A DIA', 250)